services:
  - type: web
    name: inventory-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: postgresql://inventorydb_y6kt_user:25kAEeKbdC8C4wsppgNblIaELJoHgxZp@dpg-d8ev8od53gjs739ga610-a/inventorydb_y6kt          
      - key: ALLOWED_ORIGINS
        sync: https://helpful-travesseiro-b82b98.netlify.app/         # you'll paste your Netlify URL here